Repository CMU-17313Q/nodebb-f24-team-pawsitive, pull requests merged in 2024-10, with the labels that each got.

#26 Anonymous Post Full Feature
  config.json
  node_modules/nodebb-plugin-composer-default/package.json
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  package.json
  src/topics/create.js
Labels: Backend, Frontend, Database

#27 Added tests for anonymous feature
  dump.rdb
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  package.json
  test/topics.js
Labels: Testing

#32 Manually installing npm in deploy yml
  .github/workflows/azure-deploy-f24.yml
  dump.rdb
  node_modules/nodebb-theme-harmony/templates/partials/topic/post.tpl
  package.json
Labels: bug, deployment

#34 Cleanup ignore
  .github/workflows/azure-deploy-f24.yml
  .gitignore
  dump.rdb
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/post.tpl
  package-lock.json
  package.json
Labels: bug, New Issue
